spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: fsd-gateway
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    securePortEnabled: true
    instance-id: ${spring.application.name}:${server.port}